import { explainValidPlans } from "@/lib/integrations/explanations";
import { criteriaSchema } from "@/types";
import { getWeather } from "@/lib/integrations/weather";
import { suggest } from "@/lib/integrations/xai";
import { planDates, type PlannerOptions } from ".";
import { geminiConfigured } from "@/lib/maps/config";
import { createPlannerRouter } from "@/lib/maps/routes";
import { planWithGemini } from "./gemini";

export async function generate(input: unknown, options: PlannerOptions = {}) {
  const c = criteriaSchema.parse(input);
  const weather = options.weather ?? (await getWeather(c));
  const router = options.router ?? createPlannerRouter(c.transport);
  const notices: string[] = [];
  if (geminiConfigured())
    try {
      const gemini = await planWithGemini(c, { ...options, weather, router });
      if (gemini.plans.length) {
        gemini.notices = [...notices, ...gemini.notices];
        return gemini;
      }
      notices.push(
        "Gemini could not finish a verified itinerary. These plans were generated by the local planner.",
      );
    } catch {
      notices.push(
        "AI date planning is unavailable. These plans were generated by the local planner.",
      );
    }
  let sequences: string[][] = [],
    ai = false,
    aiFailed = false;
  if (process.env.XAI_API_KEY && process.env.DISABLE_EXTERNAL_APIS !== "true")
    try {
      sequences = (await suggest(c)).sequences;
      ai = true;
    } catch {
      aiFailed = true;
    }
  const result = await planDates(c, {
    ...options,
    sequences,
    weather,
    router,
  });
  result.ai = ai;
  result.notices = [...notices, ...result.notices];
  if (weather.available && weather.advice && (weather.wet || weather.severe))
    result.notices.push(weather.advice);
  if (ai && result.plans.length) {
    try {
      result.plans = await explainValidPlans(result.plans);
    } catch {
      result.notices.push(
        "Titles and descriptions use local templates; AI wording is unavailable.",
      );
    }
  }
  if (aiFailed)
    result.notices.push(
      "AI suggestions are unavailable. These plans were generated by the local planner.",
    );
  return result;
}
