import { explainValidPlans } from "@/lib/integrations/explanations";
import { criteriaSchema } from "@/types";
import { getWeather } from "@/lib/integrations/weather";
import { suggest } from "@/lib/integrations/xai";
import { planDates, type PlannerOptions } from ".";
export async function generate(input: unknown, options: PlannerOptions = {}) {
  const c = criteriaSchema.parse(input);
  let sequences: string[][] = [],
    ai = false,
    aiFailed = false;
  if (process.env.XAI_API_KEY && process.env.DISABLE_EXTERNAL_APIS !== "true")
    try {
      sequences = (await suggest(c)).sequences;
      ai = true;
    } catch {
      aiFailed = true;
    }
  const weather = await getWeather(c),
    result = await planDates(c, { ...options, sequences, weather });
  result.ai = ai;
  if (weather.available && weather.advice && (weather.wet || weather.severe))
    result.notices.push(weather.advice);
  if (ai && result.plans.length) {
    try {
      result.plans = await explainValidPlans(result.plans);
    } catch {
      result.notices.push(
        "Titles and descriptions use local templates; AI wording is unavailable.",
      );
    }
  }
  if (aiFailed)
    result.notices.push(
      "AI suggestions are unavailable. These plans were generated by the local planner.",
    );
  return result;
}
